Repository numericalEFT/ElectronGas.jl, pull requests merged in 2022-01, with the labels that each got.

#18 Parameter
  .gitignore
  src/convention.jl
  src/interaction.jl
  src/legendreinteraction.jl
  src/parameter.jl
  src/polarization.jl
  src/selfenergy.jl
  test/interaction.jl
  test/legendreinteraction.jl
  test/polarization.jl
  test/runtests.jl
  test/selfenergy.jl
Labels: enhancement

#19 add some notes
  Project.toml
  docs/make.jl
  docs/src/lib/convention.md
  docs/src/lib/interaction.md
  docs/src/lib/legendreinteraction.md
  docs/src/lib/parameter.md
  docs/src/lib/polarization.md
  docs/src/lib/selfenergy.md
  docs/src/manual/legendreinteraction.md
  docs/src/manual/polarization.md
Labels: documentation

#23 Dev
  src/interaction.jl
  src/parameter.jl
  test/interaction.jl
  test/legendreinteraction.jl
  test/polarization.jl
  test/selfenergy.jl
Labels: documentation

#24 add support for Fock sigma
  .gitignore
  docs/make.jl
  docs/src/assets/fock_UEG_3D.png
  docs/src/assets/lindhard_function.png
  docs/src/assets/polarization.png
  docs/src/assets/polarization.svg
  docs/src/assets/polarization.svg.2020_07_21_14_31_14.0.svg
  docs/src/manual/fock.md
  src/parameter.jl
  src/selfenergy.jl
  test/selfenergy.jl
Labels: documentation, enhancement
